# goal of the action, since this is a general action, a string is ok
string bt_action_goal
actionlib_msgs/GoalID goal_id
---
# result of the action, SUCCESS, FAILURE, RUNNING
string bt_status
---
# feedback is the same as the result for a BT action
string bt_status
