# update frequency of the action servers
# determines how often they check for pre-empts and completion
action_update_freq : 10
# update frequency of servo controls
controller_update_freq : 10
# duh
max_rpm : 2000
max_fin_radians : 0.6
# How aggressive lolo will be when using rudders
# 0 = dont use at all, 999 = bang-bang, 50 = a nice number tuned in sim
# if set to 0, the only way lolo can turn is with thrusters
rudder_Kp : 50

# A cone in front of lolo where it will turn using just the rudders
# for yaw-control, if the target point is outside this cone
# then it will use thrusters to turn in place towards until it is
# measured from the centerline of the cone
rudder_cone_degrees : 18

