namespace: sam
monitor:
  - topic:
      name: core/dvl_raw
      freq: 0.1 # If the DVL is gone for more than 10 sec, abort mission
  - topic:
      name: core/imu
      freq: 20.
  - topic:
      name: core/sbg_imu
      freq: 50.
  - topic:
      name: core/heartbeat
      freq: 3.
  - topic:
      name: core/leak
      freq: 4.
  - topic:
      name: core/vbs_fb
      freq: 5.
  - topic:
      name: core/thruster1_fb
      freq: 10.
  - topic:
      name: core/thruster2_fb
      freq: 10.
  - topic:
      name: core/depth20_pressure
      freq: 10.
  - topic:
      name: uwcomms/heartbeat
      freq: 0.1