# This holds the id of the task
uint64 task_id

# Termination condition WP: X. Set to zero if not used
float64 x

# Termination condition WP: Y. Set to zero if not used
float64 y

# Termination condition WP: depth. Set to zero if not used
float64 depth

# Termination condition WP: altitude. Set to zero if not used
float64 altitude

# Termination condition WP: Yaw. Set to zero if not used
float64 theta

# Termination condition: maximum duration of the task. Set to zero if not used
duration max_duration

# Action server topic
string action_topic

# Additional arguments to the action server call
string action_arguments
